### ISSUE TITLE
Currently working?

### ISSUE THREAD

**Issue by c0nn3r** [jarfo/kchar#1]
Is this implementation currently working for you @jarfo? I currently get a large amount of errors when trying to run it.

**Comment by jarfo** [comment]
There is currently a open issue in Keras respect with the sparse_categorical_crossentropy loss https://github.com/fchollet/keras/issues/2792

As a workaround, I have updated the code to use the categorical_crossentropy loss.

**Comment by c0nn3r** [comment]
Thanks so much! I will see what I can do for that issue.
