### ISSUE TITLE
What is the task at hand ?

### ISSUE THREAD

**Issue by anujgupta82** [jarfo/kchar#10]
May be a naive question - but its not very clear whats the _task at hand_.
When I looking I training data - its a series of sentences. So is it the task to predict (k+1)th word after looking at 1....k words ?

**Comment by jarfo** [comment]
Right. with the idea of computing the probability of the whole sentence, i.e., Language modelingLanguage modeling is used in speech recognition, machine translation, part-of-speech tagging, parsing, handwriting recognition, information retrieval and other applications.

    En martes, 21 de noviembre de 2017 8:14:31 CET, Anuj-Gupta <notifications@github.com> escribió:  
 
 
May be a naive question - but its not very clear whats the task at hand.
When I looking I training data - its a series of sentences. So it the task to predict (k+1)th word after looking at 1....k words ?
