### ISSUE TITLE
tcmalloc alert

### ISSUE THREAD

**Issue by adelra** [jarfo/kchar#11]
While using this code on large datasets, I face the tcmalloc alert and the process is killed. What could be a solution to this? Can we process the data on several batches?

`tcmalloc: large alloc 26052075520 bytes == 0x1fbca000 @  0x7f4a26405f21 0x7f4a23f93ae5 0x7f4a23ff68d3 0x7f4a23ff8816 0x7f4a24090b28 0x4c4b0b 0x54f3c4 0x551ee0 0x54efc1 0x54f24d 0x553aaf 0x54e4c8 0x5582c2 0x459c11 0x45969e 0x4e0b5b 0x4da8d7 0x459893 0x54f117 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54ff73 0x42b3c9 0x42b5b5 0x44182b 0x421f64 0x7f4a2524d1c1 0x42201a
`

**Comment by jarfo** [comment]
You can try smaller batch sizes, but I am not sure it is a batch problem. You would need first to identify the specific python code that causes that large allocation.

**Comment by adelra** [comment]
This log might be helpful:

```
...
After first pass of data, max word length is: 674
Token count: train 100200269, val 17831, test 3877
tcmalloc: large alloc 26052075520 bytes == 0x1fbca000 @  0x7f4a26405f21 0x7f4a23f93ae5 0x7f4a23ff68d3 0x7f4a23ff8816 0x7f4a24090b28 0x4c4b0b 0x54f3c4 0x551ee0 0x54efc1 0x54f24d 0x553aaf 0x54e4c8 0x5582c2 0x459c11 0x45969e 0x4e0b5b 0x4da8d7 0x459893 0x54f117 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54ff73 0x42b3c9 0x42b5b5 0x44182b 0x421f64 0x7f4a2524d1c1 0x42201a
Killed
```

I will try to reduce the batch size and test the results.

**Comment by adelra** [comment]
I tried multiple configurations, decreasing all the hyperparameters but the allocated size does not seem to decrease. I even tried with another server with 30gb of ram but I faced the same error.

**Comment by jarfo** [comment]
The memory problem is in the preprocessing stage. Line 195 of BatchLoaderUnk.py preallocate numpy array for all the database. In your case that means 100200269 * 64 * 4 bytes, where 64 is the max word length (characters per word).

            # Preallocate the tensors we will need.
            # Watch out the second one needs a lot of RAM.
            output_tensor = np.empty(split_counts[split], dtype='int32')
            output_chars = np.zeros((split_counts[split], max_word_l), dtype='int32')

The standard solution is to distribute the full database in shards (but the data generator is not prepared for that). You can also reduce the max word lenght with the --max_word_l train option.
