### ISSUE TITLE
shape of char input?

### ISSUE THREAD

**Issue by yongzhuo** [jarfo/kchar#14]
@jarfo  I couldn't understand why the shape of char layer  is (opt.batch_size, opt.seq_length, opt.max_word_l), eg. (20, 35, 21); why not (batch_size, seq_length), eg.(20, 35)?

**Comment by jarfo** [comment]
Seq_lenght (35) is the number of words in each batch sequence and max_word_l the maximum number of characters of each word. The input of the LSTM are word embeddings obtained from embeddings of all the characters of each word. The three dimensions of the input allow us to obtain the (opt.batch_size, opt.seq_length, word_embedding_size) required at the input of the LSTM

**Comment by yongzhuo** [comment]
ok, thanks!
