### ISSUE TITLE
Tensorflow support?

### ISSUE THREAD

**Issue by subramanyam86** [jarfo/kchar#3]
Hi,
I was running into some issues running your code on keras with a tensorflow backend.

```
ValueError: The shape for while/Merge_2:0 is not an invariant for the loop. It enters the loop with shape (35, 21), but has shape (20, 21, 15) after one iteration. Provide shape invariants using either the `shape_invariants` argument of tf.while_loop or set_shape() on the loop variables.
```

Is this something you are aware of ?

Thanks so much for your work on this by the way!

**Comment by jarfo** [comment]
It seems a general keras issue with the TimeDistributed wrapper and the tensorflow backend as you have already mentioned in:
https://github.com/fchollet/keras/issues/4008

**Comment by jarfo** [comment]
Using the unrolled version of tensorflow rnn solves the issue. In keras/layers/wrappers.py you can change 
            if K.backend() == 'tensorflow' and len(input_shape) > 3:
to
            if K.backend() == 'tensorflow':
to use always the unrolled version with tensorflow while the keras team solves the issue.
I have already created a comment to a related recent keras change:
https://github.com/fchollet/keras/commit/99bd066f38ac9603a5c00b2eab57f6d15412ddc2

**Comment by subramanyam86** [comment]
Thanks! That works for now, will close this.
