### ISSUE TITLE
Tensorflow training incremental

### ISSUE THREAD

**Issue by prasadii** [jarfo/kchar#5]
I had trained a system with some sentences(say 10000 sentences) and i want to train the system with 200 more sentences using training incremental. How can i achieve this using this model, so that i  can train a system with total10200 sentences.
  
       Thanks in advance...

**Comment by jarfo** [comment]
The kchar software is not prepared for incremental training, and it is not easy to obtain good results using incremental training.You can always update a previous model with new data. You just need to load the old weights and fit the model with the new data.But the system will tend to (over)fit only to the new data and forget the old data after a few epochs
