### ISSUE TITLE
'--skip_train' ValueError: ('Could not interpret optimizer identifier:', <class 'keras.optimizers.SGD'>)

### ISSUE THREAD

**Issue by jingweimo** [jarfo/kchar#8]
For a quick test, I first test on a small model by running the code:
`python train_lstm3.py --rnn_size 50 --highway_layer 1 --feature_maps 5 10 15 20 25 30 --kernels 1 2 3 4 5 6 --checkpoint_dir LSTM4 --savefile char-small --max_epochs 1`

It gives the results:
Epoch 1/1
1327/1327 [==============================] - 2175s - loss: 6.6535
Epoch 1/1. Validation loss: 708.149629583
Perplexity on test set:  672.399581347

With the trained model, I perform evaluation on the test again by running the codes:
`python train_lstm3.py --rnn_size 50 --highway_layer 1 --feature_maps 5 10 15 20 25 30 --kernels 1 2 3 4 5 6 --checkpoint_dir LSTM4 --savefile char-small --max_epochs 1 --skip_train`

But it gives the error message:
`C:\Users\jingweimo\Anaconda2\lib\site-packages\keras\legacy\layers.py:654: UserWarning: The `Highway` layer is deprecated and will be removed after 06/2017.
  warnings.warn('The `Highway` layer is deprecated '

Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main(params)
  File "train.py", line 46, in main
    model = load_model('{}/{}.json'.format(opt.checkpoint_dir, opt.savefile))
  File "D:\LSTM packages\kchar-master\kchar-master\model\LSTMCNN.py", line 190, in load_model
    model.compile(loss='sparse_categorical_crossentropy', optimizer=SGD)
  File "C:\Users\jingweimo\Anaconda2\lib\site-packages\keras\engine\training.py", line 720, in compile
    self.optimizer = optimizers.get(optimizer)
  File "C:\Users\jingweimo\Anaconda2\lib\site-packages\keras\optimizers.py", line 710, in get
    identifier)
ValueError: ('Could not interpret optimizer identifier:', <class 'keras.optimizers.SGD'>)`

It seems there is something wrong with `load_model` in `LSTMCNN.py`.  I feel you may need to change 
`model.compile(loss='sparse_categorical_crossentropy', optimizer=SGD)`
to
`model.compile(loss='sparse_categorical_crossentropy', optimizer=SGD())`

**Comment by priyanka-chaudhary** [comment]
@jingweimo , @jarfo : Did you find reason/solution for this? I am facing similar problem

**Comment by gracecxj** [comment]
I am facing the same problem now, any suggestions?

**Comment by priyanka-chaudhary** [comment]
@gracecxj : My problem was similar to this and see my comment for answer
https://stackoverflow.com/questions/50056356/could-not-interpret-optimizer-identifier-error-in-keras/50066670#50066670
